# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "medieval"
  s.version = "0.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["rdinca"]
  s.date = "2015-11-02"
  s.description = "This is a medieval names generator, inspired by faker gem. In the future it will be used for an medieval online strategy game."
  s.email = "radudinca@yahoo.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/extras/array.rb",
    "lib/medieval.rb",
    "lib/medieval/attributes.rb",
    "lib/medieval/battalion.rb",
    "lib/medieval/realm.rb",
    "lib/medieval/soldier.rb",
    "medieval.gemspec",
    "rdoc/classes/Medieval/Battalion.html",
    "rdoc/classes/Medieval/Realm.html",
    "rdoc/classes/Medieval/Soldier.html",
    "rdoc/files/lib/extras/array_rb.html",
    "rdoc/files/lib/medieval/battalion_rb.html",
    "rdoc/files/lib/medieval/realm_rb.html",
    "rdoc/files/lib/medieval/soldier_rb.html",
    "rdoc/files/lib/medieval_rb.html",
    "test/helper.rb",
    "test/test_medieval.rb"
  ]
  s.homepage = "http://github.com/rdinca/medieval"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Medieval random names generator and more!"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

